### ISSUE TITLE
为什么SimTrace里的self.__parse_raw()不能删掉？

### ISSUE THREAD

**Issue by Jack0Chan** [Jack0Chan/pyuppaal#15]
# 涉及branch

api_adjust

# 问题描述

如图，`self.__parse_raw()`出于性能考虑改成了默认在构建时不parse，需要parse的时候自动判断是否需要parse(`self.__has_parse_raw`)。现在想要把这一行删除，但是删掉就跑不过pytest。

![image](https://user-images.githubusercontent.com/48609550/195814250-0d82f732-e723-4944-b7b2-a0a6b8c69d88.png)

# 需求描述

1. 找到`SimTrace.__init__()`中最后一行`self.__parse_raw()`不能删除的原因；
2. 尝试删除`self.__parse_raw()`，并通过pytest，以实现提高性能的目的。

# 其他说明

pytest使用方法
```
pip install pytest
cd path_to_pyuppaal_tests
pytest
```

pytest会自动collect我们写的test并且运行。

**Comment by yanglinshu** [comment]
Fixed in commit 19472eb4d41dab1967dc61feeceda6371526e674
