### ISSUE TITLE
utap无法在非Windows环境import

### ISSUE THREAD

**Issue by Jack0Chan** [Jack0Chan/pyuppaal#16]
# 涉及branch

api_adjust

# 问题描述

MacOS下无法通过pytest，报错内容如下图，关键信息：

```shell
No module named `pyuppaal.utap.utap_39`.
```

![image](https://user-images.githubusercontent.com/48609550/195815637-161c709b-b470-466f-b53b-8e97b00f36f0.png)

# 我们的检查

1. 换另一台Windows电脑运行pytest，通过测试；
2. 检查MacOS的python的具体版本，和Windows一致，均为`3.9.12`。

# 需求

在至少Ubuntu下通过pytest。

**Comment by wzqvip** [comment]
编译了多平台的UTAP命令行工具。
