### ISSUE TITLE
No err raised when verifyta raises an error.

### ISSUE THREAD

**Issue by Jack0Chan** [Jack0Chan/pyuppaal#25]
#17 In this issue, we ignored std_err from the terminal while using verifyta. However, we fix this by ignoring all std_err, which causes additional problems like :

"if an .xml model is not valid, verifyta raises error, but pyuppaal cannot catch it."

A potential method is to check whether "counter example" is in the std_err. 
```python
verifyta_res = xxx
if "counter example" in verifyta_res:
    regard it as normal message.
if not:
    raise this error.

```

**Comment by wzqvip** [comment]
Using _"Writing example trace to"_ as keyword.
